config/routes.rb
Rails.application.routes.draw do
  root to: 'home#top'
  get '/' => 'home#top'
  get '/about' => 'home#about'
  get '/policy' => 'home#privacy_policy'
  get '/terms' => 'home#terms'
  get 'users/show'

  resources :news
  resources :contacts
  resources :questions do
    resources :comments
  end
  resources :categories

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  # ゲストログイン機能
  devise_scope :user do
    post 'users/guest' => 'users/sessions#guest_login'
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_many :question_categories, dependent: :destroy
  has_many :categories, through: :question_categories
  has_many :comments, dependent: :destroy
  validates :title, :content, presence: true, uniqueness: { case_sensitive: true }
  validates :title, length: { minimum: 4, maximum: 25 }
  validates :content, length: { minimum: 5, maximum: 500 }

  accepts_nested_attributes_for :categories, allow_destroy: true
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: %i[show edit update destroy]
  before_action :authenticate_user!, only: %i[index show]

  add_breadcrumb '相談一覧', :questions_path

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.paginate(page: params[:page], per_page: 6)
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @question_categories = @question.categories
    @user = @question.user
    @comment = @question.comments.build
    add_breadcrumb '質問詳細', :question_path
  end

  # GET /questions/new
  def new
    @question = Question.new
    add_breadcrumb '質問作成', :new_question_path
  end

  # GET /questions/1/edit
  def edit
    add_breadcrumb '質問編集', :edit_question_path
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = current_user.questions.new(question_params)
    @category_ids = @question.categories.pluck(:id)

    respond_to do |format|
      if @question.save
        @category_ids.each(&:save)
        category_id.save
        format.html { redirect_to @question, notice: '投稿に成功しました！' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: '保存に成功しました！' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: '削除に成功しました' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_question
    @question = Question.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def question_params
    params.require(:question).permit(:title, :content, :user_id, :best_answer_id, category_ids: [])
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_comments.html.erb
<div class="container justify-content-around">
  <%= form_with(model: [@question, @comment], local: true) do |form| %>
    <div class="row text-center">
      <div class="card shadow-sm mt-3 h-75" style="height: 900px; width: 1600px;">
        <div class="card-body my-3">
          <h5 class="card-title">コメント内容<%= form.text_area :content, class: "form-control" %></h5>
          <%= form.hidden_field :question_id, value: @question.id %>
          <div class="actions">
            <%= form.submit "コメントする", class: "btn btn-success btn-lg my-3" %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/questions/_form.html.erb
<%= form_with(model: question, local: true) do |form| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>
      <ul>
        <% question.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="container justify-content-around">
    <div class="row text-center">
      <div class="card shadow-sm my-3 h-75" style="height: 900px; width: 1600px;">
        <h5 class="card-header">タイトル
          <div class="container my-2">
            <div class="form-group">
              <%= form.text_field :title, class: "form-control", placeholder: "タイトル" %>
            </div>
          </div>
        </h5>
        <div class="card-body">
          <h5 class="card-title">投稿内容
            <div class="container my-2">
              <%= form.text_area :content, class: "form-control" %>
            </div>
          </h5>
          <h5 class="container">タグ
            <%= form.collection_check_boxes :category_ids, Category.all, :id, :name, include_hidden: false do |category| %>
              <div class="form-check form-check-inline">
                <%= category.check_box class: "form-check-input" %>
                <%= category.label { category.text } %>
              </div>
            <% end %>
          </h5>
          <div class="actions">
            <%= form.submit "投稿", class: "btn btn-success btn-lg my-3" %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="container my-4">
    <hr>
  </div>
<% end %>

app/views/questions/_posted.html.erb
<h2 class="my-5">相談へのコメント</h2>

<div class="container justify-content-center">
  <div class="row row-cols-1 row-cols-md-2">
    <% @question.comments.each do |comment| %>
      <% if comment.content? %>
        <div class="col mb-3">
          <div class="card text-center shadow-sm my-5 h-75" style="height: 300px;">
            <div class="card-body mt-3">
            <% if @question.best_answer_id == comment.id %>
              <strong>⭐︎ベストコメント⭐︎</strong><br>
            <% end %>
              <h5 class="card-text"><%= comment.content %></h5>
              <p class="card-text text-right text-muted">
                投稿者：
                <% if @user.image? %>
                  <%= image_tag @user.image.mini.url %>
                <% else %>
                <% end %>
                <%= comment.user.name unless comment.user.blank? %>
              </p>
              <hr>
              <% if current_user == comment.user %>
                <%= link_to_unless @question.best_answer_id, "コメント削除", question_comment_path(@question, comment), method: :delete, data: { confirm: "本当に削除しますか?" }, class: 'btn btn-danger btn-sm' %>
              <% end %>
            </div>
            <% if @question.user == current_user %>
              <div class="text-center disabled<%= "disabled" if @question.best_answer_id != nil %>">
                <%= button_to "ベストコメント！", { controller: 'questions', action: 'update' },
                  { method: :put, class: "btn btn-warning btn-sm mb-4", params: { question: { title: @question.title,
                                                                                              content: @question.content,
                                                                                              user_id: @question.user_id,
                                                                                              best_answer_id: comment.id
                  }},
                  disabled: @question.best_answer_id,
                  data: { confirm: "#{ User.find_by(id: comment.user_id).name }さんの回答をベストコメントにします。この修正は変更できませんが、よろしいですか？" }
                  }
                %>
              </div>
            <% end %>
          </div>
        </div>
      <% elsif @question.best_answer_id == nil %>
        <div class="container my-4">
          <h3 class="font-italic text-muted">↓　コメントしてみましょう！　↓</h3>
        </div>
      <% else %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/questions/edit.html.erb
<div class="container my-3">
  <h1>相談内容編集</h1>
</div>

<div class="container">
  <ol class="breadcrumb">
    <%= render_breadcrumbs :tag => :li, :separator => " / " %>
  </ol>
</div>

<%= render 'form', question: @question %>

<div class="container mb-5">
  <%= link_to '戻る', questions_path, class: "btn btn-secondary btn-lg" %>
</div>

app/views/questions/index.html.erb
<div class="container my-3">
  <h1 class="mb-5">相談一覧</h1>
</div>

<div class="container">
  <ol class="breadcrumb">
    <%= render_breadcrumbs :tag => :li, :separator => " / " %>
  </ol>
</div>

<%= will_paginate @questions, list_classes: %w(pagination justify-content-center), :previous_label => ' &lt 前へ', :next_label => '次へ &gt' %>
<div class="container justify-content-center">
  <div class="row row-cols-1 row-cols-md-2">
    <% @questions.each do |question| %>
      <div class="col mb-3">
        <div class="card text-center shadow-sm my-5 h-75" style="height: 300px;">
          <h5 class="card-header">タイトル：<%= question.title %>
          <% if question.best_answer_id %>
            <span class="badge font-italic" style="color: red;" >解決済み</span>
          <% end %>
          </h5>
          <div class="card-body">
            <h5 class="card-title">
              <%= truncate(question.content, length: 30) %><br>
            </h5>
              <% question.categories.each do |category| %>
                <h5><span>
                  <%= link_to category.name, category_path(id: category.id), class: "badge badge-pill badge-secondary" %>
                </span></h5>
              <% end %>
            <div class="container my-3">
              <%= link_to '続きを読む', question, class: "btn btn-info" %>
            </div>
            <p class="card-text text-right text-muted">投稿者：
              <% if question.user.image? %>
                <%= image_tag question.user.image.mini.url %>
              <% else %>
              <% end %>
              <%= question.user.name %>
            </p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
<%= will_paginate @questions, list_classes: %w(pagination justify-content-center), :previous_label => ' &lt 前へ', :next_label => '次へ &gt' %>

<div class="container my-5">
  <hr>
</div>

<%= link_to 'カテゴリー一覧', categories_path, class: "btn btn-lg btn-primary mr-2" %>
<%= link_to 'カテゴリー作成', new_category_path, class: "btn btn-lg btn-warning" %>

<div class="container my-5">
  <%= link_to '新規質問作成', new_question_path, class: "btn btn-success btn-lg" %>
  <% unless user_signed_in? %>
    <h5 class="my-2 font-italic text-muted">ログインするとコメントできます!</h5>
  <% end %>
</div>

app/views/questions/new.html.erb
<div class="container my-3">
  <h1>新規相談作成</h1>
</div>

<div class="container">
  <ol class="breadcrumb">
    <%= render_breadcrumbs :tag => :li, :separator => " / " %>
  </ol>
</div>

<%= render 'form', question: @question %>

<%= link_to '戻る', questions_path, class: "btn btn-secondary my-3 btn-lg" %>

app/views/questions/show.html.erb
<div class="container my-3">
  <h1>質問内容</h1>
</div>

<div class="container">
  <ol class="breadcrumb">
    <%= render_breadcrumbs :tag => :li, :separator => " / " %>
  </ol>
</div>

<div class="container justify-content-around">
  <div class="row">
    <div class="card text-center my-3 h-75 shadow-sm" style="height: 900px; width: 1600px;">
      <h5 class="card-header">タイトル：<%= @question.title %></h5>
      <div class="card-body">
        <h5 class="card-title"><%= @question.content %></h5>
        <div class="card-text text-center text-muted">
          <p>投稿日時　<%= @question.updated_at.strftime("%Y年%m月%d日 %H時%m分") %></p>
        </div>
        <hr>
        <div class="container my-3">
          <% @question.categories.each do |category| %>
            <h5><%= link_to category.name, category_path(id: category.id), class: "badge badge-pill badge-secondary" %></h5>
          <% end %>
        </div>
        <div class="card-text text-right text-muted">
          <p>投稿者 
            <% if @user.image? %>
              <%= image_tag @user.image.mini.url %>
            <% else %>
              <p class="font-italic">画像がありません</p>
            <% end %>
            <%= @question.user.name %>
          </p>
        </div>
        <% if current_user.id == @question.user_id %>
          <%= link_to_unless @question.best_answer_id, "編集", edit_question_path(@question), class: "btn btn-success mx-2" %>
          <%= link_to_unless @question.best_answer_id, "削除", @question, method: :delete, class: "btn btn-danger mx-2", data: { confirm: '削除しますか?' } %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="container my-5">
  <hr>
</div>

<%= render 'posted', question: @question %>

<div class="container my-5">
  <hr>
</div>

<% unless @question.best_answer_id %>
  <h2 class="my-5">コメントする</h2>
  <%= render 'comments', question: @question %>
  <div class="container my-5">
  <hr>
</div>
<% end %>

<div class="container my-4">
  <%= link_to '相談一覧', questions_path, class: "btn btn-secondary mx-2 btn-lg" %>
</div>