config/routes.rb
Rails.application.routes.draw do
  root to: 'home#top'
  get '/' => 'home#top'
  get '/about' => 'home#about'
  get '/policy' => 'home#privacy_policy'
  get '/terms' => 'home#terms'
  get 'users/show'

  resources :news
  resources :contacts
  resources :questions do
    resources :comments
  end
  resources :categories

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  # ゲストログイン機能
  devise_scope :user do
    post 'users/guest' => 'users/sessions#guest_login'
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
    @latest_news = News.last
  end

  def about
    add_breadcrumb '概要', :about_path
  end

  def privacy_policy; end

  def terms; end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<div class="container my-3">
  <h1>CareYouの概要</h1>
</div>

<div class="container">
  <ol class="breadcrumb">
    <%= render_breadcrumbs :tag => :li, :separator => " / " %>
  </ol>
</div>

<div class="container my-5">
  <div class="card mb-3 shadow-sm">
    <div class="row no-gutters">
      <div class="col-md-4">
        <%= image_tag "free-kaigo.jpeg", class: "card-img ", alt: "介護", style: "width: 460px;" %>
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h5 class="card-title">CareYouとは</h5>
          <p class="card-text">介護にまつわる疑問や質問を、</p>
          <p class="card-text">オープンに聞くことができるQ&Aプラットフォームです。</p>
          <p class="card-text">介護に携わる方と共に、これからの介護を考えていきます。</p>
          <p class="card-text">また、介護に関するニュースも配信しています。</p>
        </div>
      </div>
    </div>
  </div>
    <div class="container my-5">
    <%= link_to "相談一覧", questions_path, class: "btn btn-info btn-lg mx-1" %>
    <%= link_to "相談してみる", new_question_path, class: "btn btn-success btn-lg mx-1" %>
  </div>
    <div class="container mb-5">
    <%= link_to "ニュース一覧", news_index_path, class: "btn btn-warning btn-lg mx-1" %>
  </div>
</div>

app/views/home/privacy_policy.html.erb
<div class="container my-5">
  <div class="container my-3">
    <h1>プライバシーポリシー</h1>
    <p>CareYou（以下，「当サイト」といいます）は，本ウェブサイト上で提供するサービス（以下，「本サービス」といいます）における，ユーザーの個人情報の取扱いについて，以下のとおりプライバシーポリシー（以下，「本ポリシー」といいます）を定めます。</p>
  </div>
  <div class="container my-3">
    <hr>
  </div>

  <div class="container my-3">
    <ul>
      <li>第1条（個人情報）</li>
      <p>「個人情報」とは，個人情報保護法にいう「個人情報」を指すものとし，生存する個人に関する情報であって，当該情報に含まれる氏名，連絡先その他の記述等により特定の個人を識別できる情報及び容貌にかかるデータなどの当該情報単体から特定の個人を識別できる情報（個人識別情報）を指します。</p>
      <div class="container my-3">
        <hr>
      </div>

      <li>第2条（個人情報の収集方法）</li>
      <p>当サイトは，ユーザーが利用登録をする際に氏名，メールアドレスなどの個人情報をお尋ねすることがあります。また，ユーザーと提携先などとの間でなされたユーザーの個人情報を含む情報を，当サイトの提携先（情報提供元，広告主，広告配信先などを含みます 以下，｢提携先｣といいます）などから収集することがあります。</p>
      <div class="container my-3">
        <hr>
      </div>

      <li>第3条（個人情報を収集・利用する目的）</li>
      <p>当サイトが個人情報を収集・利用する目的は，以下のとおりです。</p>
      <ul>
        <li><p>当サイトサービスの提供・運営のため</p></li>
        <li><p>ユーザーからのお問い合わせに回答するため（本人確認を行うことを含む）</p></li>
        <li><p>ユーザーが利用中のサービスの新機能，更新情報，キャンペーン等及び当サイトが提供する他のサービスの案内のメールを送付するため</p></li>
        <li><p>メンテナンス，重要なお知らせなど必要に応じたご連絡のため</p></li>
        <li><p>利用規約に違反したユーザーや，不正・不当な目的でサービスを利用しようとするユーザーの特定をし，ご利用をお断りするため</p></li>
        <li><p>ユーザーにご自身の登録情報の閲覧や変更，削除，ご利用状況の閲覧を行っていただくため</p></li>
        <li><p>上記の利用目的に付随する目的</p></li>
      </ul>
      <div class="container my-3">
        <hr>
      </div>

      <li>第4条（利用目的の変更）</li>
      <p>当サイトは，利用目的が変更前と関連性を有すると合理的に認められる場合に限り，個人情報の利用目的を変更するものとします。
      利用目的の変更を行った場合には，変更後の目的について，当サイト所定の方法により，ユーザーに通知し，または本ウェブサイト上に公表するものとします。</p>
      <div class="container my-3">
        <hr>
      </div>

      <li>第5条（個人情報の第三者提供）</li>
      <p>当サイトは，次に掲げる場合を除いて，あらかじめユーザーの同意を得ることなく，第三者に個人情報を提供することはありません。ただし，個人情報保護法その他の法令で認められる場合を除きます。</p>
      <ul>
        <li><p>人の生命，身体または財産の保護のために必要がある場合であって，本人の同意を得ることが困難であるとき</p></li>
        <li><p>公衆衛生の向上または児童の健全な育成の推進のために特に必要がある場合であって，本人の同意を得ることが困難であるとき</p></li>
        <li><p>国の機関もしくは地方公共団体またはその委託を受けた者が法令の定める事務を遂行することに対して協力する必要がある場合であって，本人の同意を得ることにより当該事務の遂行に支障を及ぼすおそれがあるとき</p></li>
        <li><p>予め次の事項を告知あるいは公表し，かつ当サイトが個人情報保護委員会に届出をしたとき</p></li>
        <li><p>利用目的に第三者への提供を含むこと</p></li>
        <li><p>第三者に提供されるデータの項目</p></li>
        <li><p>第三者への提供の手段または方法</p></li>
        <li><p>本人の求めに応じて個人情報の第三者への提供を停止すること</p></li>
        <li><p>本人の求めを受け付ける方法</p></li>
      </ul>
      <p>前項の定めにかかわらず，次に掲げる場合には，当該情報の提供先は第三者に該当しないものとします。
      <ul>
        <li><p>当サイトが利用目的の達成に必要な範囲内において個人情報の取扱いの全部または一部を委託する場合</p></li>
        <li><p>合併その他の事由による事業の承継に伴って個人情報が提供される場合</p></li>
        <li><p>個人情報を特定の者との間で共同して利用する場合であって，その旨並びに共同して利用される個人情報の項目，共同して利用する者の範囲，利用する者の利用目的および当該個人情報の管理について責任を有する者の氏名または名称について，あらかじめ本人に通知し，または本人が容易に知り得る状態に置いた場合</p></li>
      </ul>
      <div class="container my-3">
        <hr>
      </div>

      <li>第6条（個人情報の開示）</li>
      <p>当サイトは，本人から個人情報の開示を求められたときは，本人に対し，遅滞なくこれを開示します。ただし，開示することにより次のいずれかに該当する場合は，その全部または一部を開示しないこともあり，開示しない決定をした場合には，その旨を遅滞なく通知します。</p>
      <ul>
        <li><p>当サイトの業務の適正な実施に著しい支障を及ぼすおそれがある場合</p></li>
        <li><p>本人または第三者の生命，身体，財産その他の権利利益を害するおそれがある場合</p></li>
        <li><p>その他法令に違反することとなる場合</p></li>
      </ul>
      <p>前項の定めにかかわらず，履歴情報および特性情報などの個人情報以外の情報については，原則として開示いたしません。</p>
      <div class="container my-3">
        <hr>
      </div>

      <li>第7条（個人情報の訂正および削除）</li>
      <p>ユーザーは，当サイトの保有する自己の個人情報が誤った情報である場合には，当サイトが定める手続きにより，当サイトに対して個人情報の訂正，追加または削除（以下，「訂正等」といいます。）を請求することができます。
      当サイトは，ユーザーから前項の請求を受けてその請求に応じる必要があると判断した場合には，遅滞なく，当該個人情報の訂正等を行うものとします。
      当サイトは，前項の規定に基づき訂正等を行った場合，または訂正等を行わない旨の決定をしたときは遅滞なく，これをユーザーに通知します。</p>
      <div class="container my-3">
        <hr>
      </div>

      <li>第8条（個人情報の利用停止等）</li>
      <p>当サイトは，本人から，個人情報が，利用目的の範囲を超えて取り扱われているという理由，または不正の手段により取得されたものであるという理由により，その利用の停止または消去（以下，「利用停止等」といいます。）を求められた場合には，遅滞なく必要な調査を行います。
      前項の調査結果に基づき，その請求に応じる必要があると判断した場合には，遅滞なく，当該個人情報の利用停止等を行います。
      当サイトは，前項の規定に基づき利用停止等を行った場合，または利用停止等を行わない旨の決定をしたときは，遅滞なく，これをユーザーに通知します。
      前2項にかかわらず，利用停止等に多額の費用を有する場合その他利用停止等を行うことが困難な場合であって，ユーザーの権利利益を保護するために必要なこれに代わるべき措置をとれる場合は，この代替策を講じるものとします。</p>
      <div class="container my-3">
        <hr>
      </div>

      <li>第9条（プライバシーポリシーの変更）</li>
      <p>本ポリシーの内容は，法令その他本ポリシーに別段の定めのある事項を除いて，ユーザーに通知することなく，変更することができるものとします。
      当サイトが別途定める場合を除いて，変更後のプライバシーポリシーは，本ウェブサイトに掲載したときから効力を生じるものとします。</p>
      <div class="container my-3">
        <hr>
      </div>

      <li>第10条（お問い合わせ窓口）</li>
      <p>本ポリシーに関するお問い合わせは，下記の窓口までお願いいたします。</p>
    </ul>
  </div>
  <div class="container my-3">
    <hr>
  </div>
  <p>担当者：Permz</p>
  <p>メールアドレス：sakanaquarium0mashim0@gmail.com</p>
</div>

app/views/home/terms.html.erb
<div class="container my-5">
  <div class="container my-3">
    <h1>利用規約</h1>
    <p>この利用規約（以下，「本規約」といいます）は，CareYou（以下，「当サイト」といいます）がこのウェブサイト上で提供するサービス（以下，「本サービス」といいます）の利用条件を定めるものです。登録ユーザーの皆さま（以下，「ユーザー」といいます）には，本規約に従って，本サービスをご利用いただきます。</p>
  </div>
  <div class="container my-3">
    <hr>
  </div>
  <div class="container my-3">
    <ul>
      <li>第1条（適用）</li>
      <p>本規約は，ユーザーと当サイトとの間の本サービスの利用に関わる一切の関係に適用されるものとします。
      当サイトは本サービスに関し，本規約のほか，ご利用にあたってのルール等，各種の定め（以下，「個別規定」といいます。）をすることがあります。これら個別規定はその名称のいかんに関わらず，本規約の一部を構成するものとします。
      本規約の規定が前条の個別規定の規定と矛盾する場合には，個別規定において特段の定めなき限り，個別規定の規定が優先されるものとします。</p>
      <div class="container my-3">
        <hr>
      </div>

      <li>第2条（利用登録）</li>
      <p>本サービスにおいては，登録希望者が本規約に同意の上，当サイトの定める方法によって利用登録を申請し，当サイトがこの承認を登録希望者に通知することによって，利用登録が完了するものとします。
      当サイトは，利用登録の申請者に以下の事由があると判断した場合，利用登録の申請を承認しないことがあり，その理由については一切の開示義務を負わないものとします。</p>
      <ul>
        <li><p>利用登録の申請に際して虚偽の事項を届け出た場合</p></li>
        <li><p>本規約に違反したことがある者からの申請である場合</p></li>
        <li><p>その他，当サイトが利用登録を相当でないと判断した場合</p></li>
      </ul>
      <div class="container my-3">
        <hr>
      </div>

      <li>第3条（ユーザーIDおよびパスワードの管理）</li>
      <p>ユーザーは，自己の責任において，本サービスのユーザーIDおよびパスワードを適切に管理するものとします。
      ユーザーは，いかなる場合にも，ユーザーIDおよびパスワードを第三者に譲渡または貸与し，もしくは第三者と共用することはできません。当サイトは，ユーザーIDとパスワードの組み合わせが登録情報と一致してログインされた場合には，そのユーザーIDを登録しているユーザー自身による利用とみなします。
      ユーザーID及びパスワードが第三者によって使用されたことによって生じた損害は，当サイトに故意又は重大な過失がある場合を除き，当サイトは一切の責任を負わないものとします。</p>
      <div class="container my-3">
        <hr>
      </div>


      <li>第4条（禁止事項）</li>
      <p>ユーザーは，本サービスの利用にあたり，以下の行為をしてはなりません。</p>
      <ul>
        <li><p>法令または公序良俗に違反する行為</p></li>
        <li><p>犯罪行為に関連する行為</p></li>
        <li><p>当サイト，本サービスの他のユーザー，または第三者のサーバーまたはネットワークの機能を破壊したり，妨害したりする行為</p></li>
        <li><p>当サイトのサービスの運営を妨害するおそれのある行為</p></li>
        <li><p>他のユーザーに関する個人情報等を収集または蓄積する行為</p></li>
        <li><p>不正アクセスをし，またはこれを試みる行為</p></li>
        <li><p>他のユーザーに成りすます行為</p></li>
        <li><p>当サイトのサービスに関連して，反社会的勢力に対して直接または間接に利益を供与する行為</p></li>
        <li><p>当サイト，本サービスの他のユーザーまたは第三者の知的財産権，肖像権，プライバシー，名誉その他の権利または利益を侵害する行為</p></li>
        <li><p>以下の表現を含み，または含むと当サイトが判断する内容を本サービス上に投稿し，または送信する行為</p></li>
        <li><p>過度に暴力的な表現</p></li>
        <li><p>露骨な性的表現</p></li>
        <li><p>人種，国籍，信条，性別，社会的身分，門地等による差別につながる表現</p></li>
        <li><p>自殺，自傷行為，薬物乱用を誘引または助長する表現</p></li>
        <li><p>その他反社会的な内容を含み他人に不快感を与える表現</p></li>
        <li><p>以下を目的とし，または目的とすると当サイトが判断する行為</p></li>
        <li><p>営業，宣伝，広告，勧誘，その他営利を目的とする行為（当サイトの認めたものを除く）</p></li>
        <li><p>性行為やわいせつな行為を目的とする行為</p></li>
        <li><p>面識のない異性との出会いや交際を目的とする行為</p></li>
        <li><p>他のユーザーに対する嫌がらせや誹謗中傷を目的とする行為</p></li>
        <li><p>当サイト，本サービスの他のユーザー，または第三者に不利益，損害または不快感を与えることを目的とする行為</p></li>
        <li><p>その他本サービスが予定している利用目的と異なる目的で本サービスを利用する行為</p></li>
        <li><p>宗教活動または宗教団体への勧誘行為</p></li>
        <li><p>その他，当サイトが不適切と判断する行為</p></li>
      </ul>
      <div class="container my-3">
        <hr>
      </div>


      <li>第5条（本サービスの提供の停止等）</li>
      <p>当サイトは，以下のいずれかの事由があると判断した場合，ユーザーに事前に通知することなく本サービスの全部または一部の提供を停止または中断することができるものとします。また、当サイトは，本サービスの提供の停止または中断により，ユーザーまたは第三者が被ったいかなる不利益または損害についても，一切の責任を負わないものとします。</p>
      <ul>
        <li><p>地震，落雷，火災，停電または天災などの不可抗力により，本サービスの提供が困難となった場合</p></li>
        <li><p>本サービスにかかるコンピュータシステムの保守点検または更新を行う場合</p></li>
        <li><p>コンピュータまたは通信回線等が事故により停止した場合</p></li>
        <li><p>その他，当サイトが本サービスの提供が困難と判断した場合</p></li>
      </ul>
      <div class="container my-3">
        <hr>
      </div>

      <li>第6条（著作権）</li>
      <p>ユーザーは，自ら著作権等の必要な知的財産権を有するか，または必要な権利者の許諾を得た文章，画像や映像等の情報に関してのみ，本サービスを利用し，投稿ないしアップロードすることができるものとします。
      ユーザーが本サービスを利用して投稿ないしアップロードした文章，画像，映像等の著作権については，当該ユーザーその他既存の権利者に留保されるものとします。ただし，当サイトは，本サービスを利用して投稿ないしアップロードされた文章，画像，映像等について，本サービスの改良，品質の向上，または不備の是正等ならびに本サービスの周知宣伝等に必要な範囲で利用できるものとし，ユーザーは，この利用に関して，著作者人格権を行使しないものとします。
      前項本文の定めるものを除き，本サービスおよび本サービスに関連する一切の情報についての著作権およびその他の知的財産権はすべて当サイトまたは当サイトにその利用を許諾した権利者に帰属し，ユーザーは無断で複製，譲渡，貸与，翻訳，改変，転載，公衆送信（送信可能化を含みます。），伝送，配布，出版，営業使用等をしてはならないものとします。</p>
      <div class="container my-3">
        <hr>
      </div>

      <li>第7条（利用制限および登録抹消）</li>
      <p>当サイトは，ユーザーが以下のいずれかに該当する場合には，事前の通知なく，投稿データを削除し，ユーザーに対して本サービスの全部もしくは一部の利用を制限しまたはユーザーとしての登録を抹消することができるものとします。</p>
      <ul>
        <li><p>本規約のいずれかの条項に違反した場合</p></li>
        <li><p>当サイトからの連絡に対し，一定期間返答がない場合</p></li>
        <li><p>本サービスについて，最終の利用から一定期間利用がない場合</p></li>
        <li><p>その他，当サイトが本サービスの利用を適当でないと判断した場合</p></li>
      </ul>
      <p>前項各号のいずれかに該当した場合，ユーザーは，当然に当サイトに対する一切の債務について期限の利益を失い，その時点において負担する一切の債務を直ちに一括して弁済しなければなりません。
      当サイトは，本条に基づき当サイトが行った行為によりユーザーに生じた損害について，一切の責任を負いません。</p>
      <div class="container my-3">
        <hr>
      </div>

      <li>第8条（退会）</li>
      <p>ユーザーは，当サイトの定める退会手続により，本サービスから退会できるものとします。</p>
      <div class="container my-3">
        <hr>
      </div>

      <li>第9条（保証の否認および免責事項）</li>
      <p>当サイトは，本サービスに事実上または法律上の瑕疵（安全性，信頼性，正確性，完全性，有効性，特定の目的への適合性，セキュリティなどに関する欠陥，エラーやバグ，権利侵害などを含みます。）がないことを明示的にも黙示的にも保証しておりません。
      当サイトは，本サービスに起因してユーザーに生じたあらゆる損害について一切の責任を負いません。ただし，本サービスに関する当サイトとユーザーとの間の契約（本規約を含みます。）が消費者契約法に定める消費者契約となる場合，この免責規定は適用されません。
      前項ただし書に定める場合であっても，当サイトは，当サイトの過失（重過失を除きます。）による債務不履行または不法行為によりユーザーに生じた損害のうち特別な事情から生じた損害（当サイトまたはユーザーが損害発生につき予見し，または予見し得た場合を含みます。）について一切の責任を負いません。また，当サイトの過失（重過失を除きます。）による債務不履行または不法行為によりユーザーに生じた損害の賠償は，ユーザーから当該損害が発生した月に受領した利用料の額を上限とします。
      当サイトは，本サービスに関して，ユーザーと他のユーザーまたは第三者との間において生じた取引，連絡または紛争等について一切責任を負いません。</p>
      <div class="container my-3">
        <hr>
      </div>

      <li>第10条（サービス内容の変更等）</li>
      <p>当サイトは，ユーザーに通知することなく，本サービスの内容を変更しまたは本サービスの提供を中止することができるものとし，これによってユーザーに生じた損害について一切の責任を負いません。</p>
      <div class="container my-3">
        <hr>
      </div>

      <li>第11条（利用規約の変更）</li>
      <p>当サイトは，必要と判断した場合には，ユーザーに通知することなくいつでも本規約を変更することができるものとします。なお，本規約の変更後，本サービスの利用を開始した場合には，当該ユーザーは変更後の規約に同意したものとみなします。</p>
      <div class="container my-3">
        <hr>
      </div>

      <li>第12条（個人情報の取扱い）</li>
      <p>当サイトは，本サービスの利用によって取得する個人情報については，当サイト「プライバシーポリシー」に従い適切に取り扱うものとします。</p>
      <div class="container my-3">
        <hr>
      </div>

      <li>第13条（通知または連絡）</li>
      <p>ユーザーと当サイトとの間の通知または連絡は，当サイトの定める方法によって行うものとします。当サイトは,ユーザーから,当サイトが別途定める方式に従った変更届け出がない限り,現在登録されている連絡先が有効なものとみなして当該連絡先へ通知または連絡を行い,これらは,発信時にユーザーへ到達したものとみなします。</p>
      <div class="container my-3">
        <hr>
      </div>

      <li>第14条（権利義務の譲渡の禁止）</li>
      <p>ユーザーは，当サイトの書面による事前の承諾なく，利用契約上の地位または本規約に基づく権利もしくは義務を第三者に譲渡し，または担保に供することはできません。</p>
      <div class="container my-3">
        <hr>
      </div>

      <li>第15条（準拠法・裁判管轄）</li>
      <p>本規約の解釈にあたっては，日本法を準拠法とします。
      本サービスに関して紛争が生じた場合には，当サイトの本店所在地を管轄する裁判所を専属的合意管轄とします。</p>
    </ul>
  </div>
  <div class="container my-3">
    <hr>
  </div>
  <p>以上。</p>
</div>

app/views/home/top.html.erb
<!-- スライドショー -->
<div id="carouselExampleIndicators" class="carousel slide carousel-fade" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= image_tag "kaigo_shisetsu.jpg", class: "d-block w-100", alt: "スライド1", style: "height: 550px;" %>
    </div>
    <div class="carousel-item">
      <%= image_tag "caregiver.jpeg", class: "d-block w-100", alt: "スライド2", style: "height: 550px;" %>
    </div>
    <div class="carousel-item">
      <%= image_tag "wheelchair.jpg", class: "d-block w-100", alt: "スライド3", style: "height: 550px;" %>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<!-- 最新Newsへのリンク -->
<div class="container my-5">
  <h4><%= link_to "#{@latest_news.title}", news_path(id: @latest_news.id), class: "font-italic" %></h4>
</div>

<!-- ジャンボトロン -->
<div class="container mt-5">
  <div class="jumbotron shadow-sm">
    <h2 class="display-4">CareYou</h2>
    <p class="lead">あなたと介護を考える</p>
    <hr class="my-3">
    <p>CareYouは、介護を行うあなたのための情報共有サイトです。</p>
    <div class="container mt-4">
      <%= link_to '新規会員登録', new_user_session_path, class: "btn btn-primary btn-lg shadow-sm mx-1" %>
      <%= link_to 'ゲストログイン', users_guest_path, class: "btn btn-outline-primary btn-lg shadow-sm mx-1", method: :post %>
    </div>
  </div>
</div>

<!-- 相談コーナーへの導線 -->
<div class="container mt-5">
  <div class="card shadow-sm">
    <div class="container mt-5">
      <h2>相談してみましょう</h2>
      <p>相談コーナーでは、介護の悩みを気軽に相談できます。</p>
    </div>
    <div class="container mb-5">
      <%= link_to "相談一覧", questions_path, class: "btn btn-info btn-lg mx-1" %>
      <%= link_to "相談してみる", new_question_path, class: "btn btn-success btn-lg mx-1" %>
    </div>
  </div>
</div>

<!-- ニュースコーナーへの導線 -->
<div class="container my-5">
  <div class="card shadow-sm">
    <div class="container mt-5">
      <h2>ニュース</h2>
      <p>介護に関する最新のニュースを配信します。</p>
    </div>
    <div class="container mb-5">
      <%= link_to "ニュース一覧", news_index_path, class: "btn btn-warning btn-lg mx-1" %>
    </div>
  </div>
</div>

<!-- 概要への導線 -->
<div class="container my-5">
  <div class="card shadow-sm">
    <div class="container mt-5">
      <h2>CareYouとは</h2><%= image_tag "CareYou.png", alt: "logo", style: "width: 200px;" %>
      <p>このサイトについて紹介します。</p>
    </div>
    <div class="container mb-5">
      <%= link_to "概要", about_path, class: "btn btn-secondary btn-lg mx-1" %>
    </div>
  </div>
</div>