config/routes.rb
Rails.application.routes.draw do
  root to: 'home#top'
  get '/' => 'home#top'
  get '/about' => 'home#about'
  get '/policy' => 'home#privacy_policy'
  get '/terms' => 'home#terms'
  get 'users/show'

  resources :news
  resources :contacts
  resources :questions do
    resources :comments
  end
  resources :categories

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  # ゲストログイン機能
  devise_scope :user do
    post 'users/guest' => 'users/sessions#guest_login'
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
end

app/models/news.rb
class News < ApplicationRecord
  belongs_to :user
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_news, only: %i[show edit update destroy]
  before_action :authenticate_user!, only: %i[index show]
  before_action :not_manager, only: %i[new edit update destroy]

  add_breadcrumb 'ニュース一覧', :news_index_path

  # GET /news
  # GET /news.json
  def index
    @newss = News.paginate(page: params[:page], per_page: 6)
  end

  # GET /news/1
  # GET /news/1.json
  def show
    add_breadcrumb 'ニュース詳細', :news_path
    @user = User.find_by(id: @news.user_id)
  end

  # GET /news/new
  def new
    @news = News.new
  end

  # GET /news/1/edit
  def edit; end

  # POST /news
  # POST /news.json
  def create
    @news = News.new(news_params)

    respond_to do |format|
      if @news.save
        format.html { redirect_to @news, notice: 'ニュースの投稿に成功しました！' }
        format.json { render :show, status: :created, location: @news }
      else
        format.html { render :new }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news/1
  # PATCH/PUT /news/1.json
  def update
    respond_to do |format|
      if @news.update(news_params)
        format.html { redirect_to @news, notice: 'ニュースの更新に成功しました！' }
        format.json { render :show, status: :ok, location: @news }
      else
        format.html { render :edit }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news.destroy
    respond_to do |format|
      format.html { redirect_to news_index_url, notice: 'ニュースの削除に成功しました' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_news
    @news = News.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def news_params
    params.require(:news).permit(:title, :content, :user_id)
  end

  def not_manager
    current_user.admin_flg == false
  end
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/news/_form.html.erb
<%= form_with(model: news, local: true) do |form| %>
  <% if news.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(news.errors.count, "error") %> prohibited this news from being saved:</h2>
      <ul>
        <% news.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="container justify-content-around">
    <div class="row text-center">
      <div class="card text-center shadow-sm my-3 h-75" style="height: 900px; width: 1600px;">
        <h5 class="card-header">タイトル<%= form.text_field :title, class: "form-control" %></h5>
        <div class="card-body">
          <h5 class="card-title">投稿内容<%= form.text_area :content, class: "form-control" %></h5>
          <div class="actions">
            <%= form.submit "投稿", class: "btn btn-success btn-lg" %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="container my-5">
    <hr>
  </div>
<% end %>

app/views/news/edit.html.erb
<div class="container my-3">
  <h1>ニュース編集</h1>
</div>

<%= render 'form', news: @news %>

<%= link_to 'Show', @news, class: "btn btn-info btn-lg mx-3" %> |
<%= link_to 'Back', news_index_path, class: "btn btn-secondary btn-lg mx-3" %>

app/views/news/index.html.erb
<div class="container my-3">
  <h1>ニュース一覧</h1>
</div>

<div class="container">
  <ol class="breadcrumb">
    <%= render_breadcrumbs :tag => :li, :separator => " / " %>
  </ol>
</div>

<% if current_user.admin_flg == true %>
  <%= link_to "ニュース投稿", new_news_path, class: "btn btn-sm btn-primary" %>
<% end %>

<%= will_paginate @newss, list_classes: %w(pagination justify-content-center), :previous_label => ' &lt 前へ', :next_label => '次へ &gt' %>
<% @newss.each do |news| %>
  <div class="row justify-content-around">
    <div class="card text-center shadow-sm my-5 h-75" style="width: 800px;">
      <h5 class="card-header">タイトル：<%= news.title %></h5>
      <div class="card-body">
        <h5 class="card-title">
          <%= truncate(news.content, length: 30) %><br>
        </h5>
        <p class="card-text text-right text-muted">投稿者：
          <% if User.find_by(id: news.user_id).image? %>
            <%= image_tag User.find_by(id: news.user_id).image.mini.url %>
          <% else %>
          <% end %>
          <%= User.find_by(id: news.user_id).name %>
        </p>
        <%= link_to '詳細', news, class: "btn btn-info btn-lg" %>
      </div>
    </div>
  </div>
<% end %>
<%= will_paginate @newss, list_classes: %w(pagination justify-content-center), :previous_label => ' &lt 前へ', :next_label => '次へ &gt' %>

<div class="container my-5">
  <hr>
</div>

app/views/news/new.html.erb
<div class="container my-3">
  <h1>ニュース記事投稿</h1>
</div>

<%= render 'form', news: @news %>

<%= link_to 'Back', news_index_path, class: "btn btn-secondary btn-lg my-3" %>

app/views/news/show.html.erb
<div class="container my-3">
  <h1>ニュース内容</h1>
</div>

<div class="container">
  <ol class="breadcrumb">
    <%= render_breadcrumbs :tag => :li, :separator => " / " %>
  </ol>
</div>

<div class="row justify-content-around">
  <div class="card text-center shadow-sm my-3 h-75" style="height: 450px; width: 800px;">
    <h5 class="card-header">タイトル：<%= @news.title %></h5>
    <div class="card-body">
      <h5 class="card-title"><%= @news.content %></h5>
      <div class="card-text text-center text-muted">
        <p>投稿日時　<%= @news.updated_at.strftime("%Y年%m月%d日 %H時%m分") %></p>
      </div>
      <p class="card-text text-right text-muted">
        投稿者：
        <% if @user.image? %>
          <%= image_tag @user.image.mini.url %>
        <% else %>
        <% end %>
        <%= @user.name %>
      </p>
      <% if current_user.id == @news.user_id %>
        <%= link_to '編集', edit_news_path(@news), class: "btn btn-success mx-2" %>
        <%= link_to '削除', @news, method: :delete, class: "btn btn-danger mx-2", data: { confirm: 'Are you sure?' } %>
      <% end %>
    </div>
  </div>
</div>

<%= link_to 'Back', news_index_path, class: "btn btn-secondary btn-lg my-5" %>