config/routes.rb
Rails.application.routes.draw do
  root to: 'home#top'
  get '/' => 'home#top'
  get '/about' => 'home#about'
  get '/policy' => 'home#privacy_policy'
  get '/terms' => 'home#terms'
  get 'users/show'

  resources :news
  resources :contacts
  resources :questions do
    resources :comments
  end
  resources :categories

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  # ゲストログイン機能
  devise_scope :user do
    post 'users/guest' => 'users/sessions#guest_login'
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:

    user ||= User.new # ゲストユーザー (未ログイン)
    true if user && user.admin_flg?

    can :access, :rails_admin
    can :manage, :all

    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, length: { minimum: 2, maximum: 10 }
  validates_uniqueness_of :name
  has_many :question_categories, dependent: :destroy
  has_many :questions, through: :question_categories
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :question
  belongs_to :user
  
  validates :content, presence: true, uniqueness: true
  validates :content, length: { minimum: 10, maximum: 500 }
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user
end

app/models/news.rb
class News < ApplicationRecord
  belongs_to :user
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_many :question_categories, dependent: :destroy
  has_many :categories, through: :question_categories
  has_many :comments, dependent: :destroy
  validates :title, :content, presence: true, uniqueness: { case_sensitive: true }
  validates :title, length: { minimum: 4, maximum: 25 }
  validates :content, length: { minimum: 5, maximum: 500 }

  accepts_nested_attributes_for :categories, allow_destroy: true
end

app/models/question_category.rb
class QuestionCategory < ApplicationRecord
  belongs_to :question
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  validates :name, presence: true, uniqueness: { case_sensitive: false }, length: { maximum: 20 }
  validates :email, presence: true, length: { maximum: 255 }
  validates :introduction, presence: false, length: { maximum: 255 }

  mount_uploader :image, ImageUploader

  has_many :questions, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :contacts, dependent: :destroy
  has_many :news, dependent: :destroy

  def self.guest
    find_or_create_by(email: 'guest@example.com') do |user|
      user.name = 'ゲストユーザー'
      user.password = SecureRandom.urlsafe_base64
      user.admin_flg = false
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:destroy]

  def create
    question = Question.find(params[:question_id])
    @comment = question.comments.build(comment_params)
    @comment.user_id = current_user.id

    respond_to do |format|
      if @comment.save
        format.html { redirect_to question, notice: '投稿に成功しました！' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { redirect_to question, alert: '投稿に失敗しました' }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @question = Question.find(params[:question_id])
    question_comment = @question.comments.find(params[:id])
    redirect_to request.referer if question_comment.user != current_user
    question_comment.destroy
    respond_to do |format|
      format.html { redirect_to request.referer, notice: 'コメント削除に成功しました' }
      format.json { head :no_content }
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end

  def correct_user
    @comment = current_user.comments.find_by(id: params[:id])
    redirect_to root_url unless @comment
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
    @latest_news = News.last
  end

  def about
    add_breadcrumb '概要', :about_path
  end

  def privacy_policy; end

  def terms; end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_news, only: %i[show edit update destroy]
  before_action :authenticate_user!, only: %i[index show]
  before_action :not_manager, only: %i[new edit update destroy]

  add_breadcrumb 'ニュース一覧', :news_index_path

  # GET /news
  # GET /news.json
  def index
    @newss = News.paginate(page: params[:page], per_page: 6)
  end

  # GET /news/1
  # GET /news/1.json
  def show
    add_breadcrumb 'ニュース詳細', :news_path
    @user = User.find_by(id: @news.user_id)
  end

  # GET /news/new
  def new
    @news = News.new
  end

  # GET /news/1/edit
  def edit; end

  # POST /news
  # POST /news.json
  def create
    @news = News.new(news_params)

    respond_to do |format|
      if @news.save
        format.html { redirect_to @news, notice: 'ニュースの投稿に成功しました！' }
        format.json { render :show, status: :created, location: @news }
      else
        format.html { render :new }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news/1
  # PATCH/PUT /news/1.json
  def update
    respond_to do |format|
      if @news.update(news_params)
        format.html { redirect_to @news, notice: 'ニュースの更新に成功しました！' }
        format.json { render :show, status: :ok, location: @news }
      else
        format.html { render :edit }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news.destroy
    respond_to do |format|
      format.html { redirect_to news_index_url, notice: 'ニュースの削除に成功しました' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_news
    @news = News.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def news_params
    params.require(:news).permit(:title, :content, :user_id)
  end

  def not_manager
    current_user.admin_flg == false
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
    add_breadcrumb '会員情報', :users_show_path
  end

  protected

  def user_params
    params.require(:user).permit(:image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def default_meta_tags
    {
      title: 'CareYou',
      description: '介護の目的は、高齢者の尊厳の保持と、有する能力に応じて自立した日常生活を支援することにあります。このサイトでは、介護に携わる方のために有意義な情報を発信しています。',
      keywords: '介護,共有,Q&A',
      icon: image_url('/favicon.ico'),
      noindex: !Rails.env.production?, # production環境以外はnoindex
      charset: 'UTF-8',
      # OGPの設定
      og: {
        title: '介護情報共有サイト',
        type: 'website',
        url: request.original_url,
        image: image_url('CareYou.png'),
        site_name: 'CareYou',
        description: '介護の目的は、高齢者の尊厳の保持と、有する能力に応じて自立した日常生活を支援することにあります。このサイトでは、介護に携わる方のために有意義な情報を発信しています。',
        locale: 'ja_JP'
      }
    }
  end
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CareYou</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= display_meta_tags(default_meta_tags) %>
    <link rel="shortcut icon" href="/favicon.ico" type="image/vnd.microsoft.icon">
    <link rel="icon" href="/favicon.ico" type="image/vnd.microsoft.icon">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <!-- ナビゲーションバー -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light shadow-sm sticky-top">
      <a class="navbar-brand" href="/">
        <img src="/favicon.ico" width="30" height="30" alt="logo" class="d-inline-block align-top" loading="lazy">CareYou
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <small class="navbar-toggler-icon"></small>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="/about">概要</a>
          </li>
          <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                相談コーナー
              </a>
              <div class="dropdown-menu shadow-sm" aria-labelledby="navbarDropdown">
                <%= link_to '相談一覧', questions_path, class: "dropdown-item" %>
                <div class="dropdown-divider"></div>
                <%= link_to '相談作成', new_question_path, class: "dropdown-item" %>
              </div>
            </li>
          <li class="nav-item">
            <a class="nav-link" href="/news">ニュース</a>
          </li>
          <!-- ログインしているかしてないかでメニュー表示が変わる -->
          <% if user_signed_in? %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                マイページ
              </a>
              <div class="dropdown-menu shadow-sm" aria-labelledby="navbarDropdown">
                <%= link_to 'プロフィール', users_show_path, class: "dropdown-item" %>
                <div class="dropdown-divider"></div>
                <%= link_to 'ログアウト', destroy_user_session_path, class: "dropdown-item", method: :delete, data: { confirm: "ログアウトしますか？" } %>
              </div>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to '新規会員登録', new_user_registration_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to 'ログイン', new_user_session_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to 'ゲストログイン', users_guest_path, class: "nav-link", method: :post %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
    <!-- deviseによる追加 -->
    <%= notice %><%= alert %>
    <div id="page-content" class="text-center">
      <%= yield %>
    </div>
  </body>

  <footer id="sticky-footer" class="mt-auto py-3 bg-light">
    <div class="container text-center">
      <p>
        <%= link_to "プライバシーポリシー", policy_path, class: "text-muted mx-2" %>
        <%= link_to "利用規約", terms_path, class: "text-muted mx-2" %>
        <%= link_to "お問い合わせ", new_contact_path, class: "text-muted mx-2" %>
      </p>
      <small class="text-muted">©︎ Permz 2020</small>
    </div>
  </footer>
</html>